//! The plugin created by the user. Note that this is not built with `cargo build` as one may expect,
//! but through a custom `rustc` invocation (see `build.sh`).
//! That means that in theory, we don't even need a `Cargo.toml` for this. But tooling plays better
//! if you have a standard setup, so we "pretend" that this is a regular old cargo-compatible project.
//! Note that this means that you cannot use the `Cargo.toml` to specify dependencies, but must do so manually.
//! through rustc.

use api::*;

/// This could have all manner of metadata, but for now, it only includes the entrypoint function.
/// The scary bits of this can be generated by a `#[derive(DylibPlugin)]` macro.
#[unsafe(no_mangle)]
pub static PLUGIN: ::api::Plugin = ::api::Plugin::new(entrypoint_generated);

/// This boilerplate can be generated by a `#[dylib_entrypoint]` proc macro.
/// That's why we already use fully qualified paths.
fn entrypoint_generated(app: *mut ::api::App) -> ::api::Result {
    // A panic inside a loaded dylib is defined to immediately terminate the host process.
    // That sucks. So let's catch the panic and report it to the host process instead.
    // The plugin is still loaded (since unloading it is *dangerous*), but it won't be doing anything anymore.
    ::std::panic::catch_unwind(|| {
        let app = unsafe { &mut *app };
        entrypoint(app)
    })
    .map_err(|payload| {
        let reason = if let ::std::option::Option::Some(s) =
            payload.downcast_ref::<&'static ::std::primitive::str>()
        {
            (*s).to_owned()
        } else if let ::std::option::Option::Some(s) =
            payload.downcast_ref::<::std::string::String>()
        {
            s.clone()
        } else {
            "<non-string panic payload>".to_owned()
        };
        ::api::rootcause::report!("Plugin panicked: {}", reason)
    })
    .flatten()
}

/// Here's where the actual user code lives.
fn entrypoint(app: &mut App) -> Result {
    app.do_a_thing()?;
    Ok(())
}
